# frozen_string_literal: true

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibon1 = 1
fibon2 = 2
total = 0
count = 0

while count < 4_000_000
  count = fibon2
  total += count if count.even?
  count = fibon1 + fibon2
  fibon1 = fibon2
  fibon2 = count
end

puts "Answer: #{total}"
